# General
alias v='nvim'
alias c='clear'
alias e='v ~/.config' 
alias r='omf reload; and tmux source-file ~/.config/tmux/tmux.conf; and clear'

# Git
alias ga='git add'
alias gaa='git add -A'
alias gb='git branch'
alias gco='git checkout'
alias gcl='git clone'
alias gc='git commit -v'
alias gd='git diff'
alias gf='git fetch'
alias gi='git init'
alias gls='git log --graph --abbrev-commit --decorate --pretty=format:\'%C(auto)%h%C(reset) - %C(bold blue)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)\' --all'
alias gm='git merge'
alias gpl='git pull'
alias gp='git push'
alias gr='git reset'
alias grb='git rebase'
alias grh='git reset --hard'
alias gst='git status -sb'
